version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432 # 左がホストコンピュータのポート/右がdocker内のpostgresのポート　ホストコンピュータの5434にアクセスするとpostgresにアクセスするようになっている。
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - lesson
networks:
  lesson: